/*
Navicat MySQL Data Transfer

Source Server         : 103.44.61.204_3306
Source Server Version : 50173
Source Host           : 68.168.143.194:3306
Source Database       : notes

Target Server Type    : MYSQL
Target Server Version : 50173
File Encoding         : 65001

Date: 2018-08-14 11:16:55
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `user_data`
-- ----------------------------
DROP TABLE IF EXISTS `user_data`;
CREATE TABLE `user_data` (
  `USERNAME` varchar(8) NOT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTENT` text NOT NULL,
  `TITLE` varchar(255) NOT NULL,
  `ADDTIME` date NOT NULL,
  `EDITTIME` date NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of user_data
-- ----------------------------
INSERT INTO `user_data` VALUES ('undefine', '4', '1、安装java（1.8版本以上）\r\n    命令查看版本号（java -version）\r\n    配置环境变量JAVA_HOME\r\n2、安装android studio\r\n    配置环境变量ANDROID_HOME:\r\n    PATH里面添加环境变量 增加：安装目录sdk	ools、增加：安装目录sdkplatform-tools\r\n3、设置SDK\r\n    打开Android SDK Manager\r\n    选中以下的选项\r\n    tools\r\n     >Android SDK Tools (24.3.4)\r\n     >Android SDK Platform-tools (23.0.1)\r\n     >Android SDK Build-tools (23.0.1)\r\n    Android 6.0(API 23)\r\n     >SDK Platform 23 1\r\n     >intel x86 Atom_64 System Image 23 3\r\n     >intel x86 Atom System Image 23 3\r\n4、安装node（版本大于5.0）\r\n    命令查看node版本号（node -version）\r\n    命令查看npm版本号（npm -version）\r\n    更换淘宝镜像（npm install -g cnpm --registry=http://registry.npm.taobao.org）\r\n5、安装git\r\n    配置环境变量PATH 添加：安装目录安装文件名in\r\n6、安装react-native命令行工具react-naive-cli\r\n    新建文件夹（尽量不在C盘）名暂定为react_native\r\n    进入这个文件夹 命令行：git clone https://github.com/facebook/react-native.git（时间会很慢）\r\n    成功后找到刚下载的文件夹。进入的react-native目录下的react-native-cli目录 命令：npm install -g\r\n7、创建工程\r\n    进入你希望创建项目的目录后，输入react-native init XXX（项目名称），等待一段时间（较慢）\r\n    成功后会发现文件夹下多出很多文件夹和文件\r\n8、开启工程\r\n    进入工程目录 命令：react-native start\r\n    在浏览器中访问http://localhost:8081/index.android.bundle?platform=android\r\n9、运行项目\r\n    进入项目目录，输入react-native run-android（第一次会很慢）\r\n10、手机上显示\r\n    第一次一般会报错\r\n    这时候我们摇一摇手机，点击Dev Settings后，点击Debug server host & port for device,设置IP和端口\r\n    这里的IP是电脑的IP，不知道的可以在命令行中输入ipconfig进行查询，端口号固定8081  \r\n    设置完成后，回到空白页面，再次摇一摇手机，选择Reload JS，程序就运行起来，出现Welcome to React Native！', 'React Native', '0000-00-00', '0000-00-00');
INSERT INTO `user_data` VALUES ('nmgwap', '3', '1、安装java（1.8版本以上）\r\n    命令查看版本号（java -version）\r\n    配置环境变量JAVA_HOME\r\n2、安装android studio\r\n    配置环境变量ANDROID_HOME:\r\n    PATH里面添加环境变量 增加：安装目录sdk	ools、增加：安装目录sdkplatform-tools\r\n3、设置SDK\r\n    打开Android SDK Manager\r\n    选中以下的选项\r\n    tools\r\n     >Android SDK Tools (24.3.4)\r\n     >Android SDK Platform-tools (23.0.1)\r\n     >Android SDK Build-tools (23.0.1)\r\n    Android 6.0(API 23)\r\n     >SDK Platform 23 1\r\n     >intel x86 Atom_64 System Image 23 3\r\n     >intel x86 Atom System Image 23 3\r\n4、安装node（版本大于5.0）\r\n    命令查看node版本号（node -version）\r\n    命令查看npm版本号（npm -version）\r\n    更换淘宝镜像（npm install -g cnpm --registry=http://registry.npm.taobao.org）\r\n5、安装git\r\n    配置环境变量PATH 添加：安装目录安装文件名in\r\n6、安装react-native命令行工具react-naive-cli\r\n    新建文件夹（尽量不在C盘）名暂定为react_native\r\n    进入这个文件夹 命令行：git clone https://github.com/facebook/react-native.git（时间会很慢）\r\n    成功后找到刚下载的文件夹。进入的react-native目录下的react-native-cli目录 命令：npm install -g\r\n7、创建工程\r\n    进入你希望创建项目的目录后，输入react-native init XXX（项目名称），等待一段时间（较慢）\r\n    成功后会发现文件夹下多出很多文件夹和文件\r\n8、开启工程\r\n    进入工程目录 命令：react-native start\r\n    在浏览器中访问http://localhost:8081/index.android.bundle?platform=android\r\n9、运行项目\r\n    进入项目目录，输入react-native run-android（第一次会很慢）\r\n10、手机上显示\r\n    第一次一般会报错\r\n    这时候我们摇一摇手机，点击Dev Settings后，点击Debug server host & port for device,设置IP和端口\r\n    这里的IP是电脑的IP，不知道的可以在命令行中输入ipconfig进行查询，端口号固定8081  \r\n    设置完成后，回到空白页面，再次摇一摇手机，选择Reload JS，程序就运行起来，出现Welcome to React Native！', 'React Native', '2018-07-22', '2018-07-22');
INSERT INTO `user_data` VALUES ('undefine', '5', '1、安装java（1.8版本以上）\n    命令查看版本号（java -version）\n    配置环境变量JAVA_HOME\n2、安装android studio\n    配置环境变量ANDROID_HOME:\n    PATH里面添加环境变量 增加：安装目录sdk	ools、增加：安装目录sdkplatform-tools\n3、设置SDK\n    打开Android SDK Manager\n    选中以下的选项\n    tools\n     >Android SDK Tools (24.3.4)\n     >Android SDK Platform-tools (23.0.1)\n     >Android SDK Build-tools (23.0.1)\n    Android 6.0(API 23)\n     >SDK Platform 23 1\n     >intel x86 Atom_64 System Image 23 3\n     >intel x86 Atom System Image 23 3\n4、安装node（版本大于5.0）\n    命令查看node版本号（node -version）\n    命令查看npm版本号（npm -version）\n    更换淘宝镜像（npm install -g cnpm --registry=http://registry.npm.taobao.org）\n5、安装git\n    配置环境变量PATH 添加：安装目录安装文件名in\n6、安装react-native命令行工具react-naive-cli\n    新建文件夹（尽量不在C盘）名暂定为react_native\n    进入这个文件夹 命令行：git clone https://github.com/facebook/react-native.git（时间会很慢）\n    成功后找到刚下载的文件夹。进入的react-native目录下的react-native-cli目录 命令：npm install -g\n7、创建工程\n    进入你希望创建项目的目录后，输入react-native init XXX（项目名称），等待一段时间（较慢）\n    成功后会发现文件夹下多出很多文件夹和文件\n8、开启工程\n    进入工程目录 命令：react-native start\n    在浏览器中访问http://localhost:8081/index.android.bundle?platform=android\n9、运行项目\n    进入项目目录，输入react-native run-android（第一次会很慢）\n10、手机上显示\n    第一次一般会报错\n    这时候我们摇一摇手机，点击Dev Settings后，点击Debug server host & port for device,设置IP和端口\n    这里的IP是电脑的IP，不知道的可以在命令行中输入ipconfig进行查询，端口号固定8081  \n    设置完成后，回到空白页面，再次摇一摇手机，选择Reload JS，程序就运行起来，出现Welcome to React Native', 'React Native', '0000-00-00', '0000-00-00');
INSERT INTO `user_data` VALUES ('nmgwap', '6', '1、四种类型证书\r\n  1.1、个人开发者   99美元/年（提供个人信息即可）\r\n  1.2、公司开发者   99美元/年\r\n  1.3、企业开发者   299美元/年\r\n  1.4、高校开发者   免费\r\n\r\n2、苹果证书\r\n  2.1、开发者证书（分为开发和发布）基证书，证明自己是开发者\r\n  2.2、appID 每个应用的独立标识\r\n  2.3、推送证书（分为开发和发布）\r\n  2.4、Provisioning Profile （PP文件）该文件是将appID、开发者证书、硬件Device绑定到一起。\r\n\r\n3、理解证书与描述文件\r\n  3.1、我们向Apple申请证书是在干什么？\r\n     我们向Apple申请证书，就是向权力机关（Apple）申请资格（开发/推送/发布...）而Apple颁发给我们的证书就是对资格的证明\r\n  3.2、申请证书时，为什么要有CSR\r\n     CSR就是提供证书时自己的不是别人的\r\n     CSR生成的同时，生成一对私钥公钥。私钥保存在本地，用来加密数据或者解密公钥加密的数据，公钥包含在CSR中。\r\n  3.3、为什么要通过.p12文件来传递证书？\r\n     因为直接从Apple下载的证书只有公钥，没有办法证明这个证书是你的。而从本地钥匙串中导出的.p12文件是包含私钥的。\r\n  3.4、Provision Proflie（描述文件）\r\n     描述应用的文件\r\n     描述文件包含App ID，Certificates，Devices，', '苹果证书笔记', '2018-07-22', '2018-07-22');
INSERT INTO `user_data` VALUES ('nmgwap', '7', '主键、外键和索引的区别\r\n\r\n\r\n	主键				外键				索引\r\n定义：	唯一标识一条记录，不能有重复	表的外键是另一个表的主键，外键	该字段没有重复值，但是可以有空值\r\n	，不能允许为空			可以有重复，可以为空\r\n作用：	用来保证数据完整性		用来和其他表建立联系用		是提高查询排序的速度\r\n个数：	主键只能有一个			一个表可以有多个外键		一个表可以有多个唯一索引\r\n', '主键，外键和索引', '2018-07-22', '2018-07-22');
INSERT INTO `user_data` VALUES ('nmgwap', '8', 'webpack用途\r\n 打包合并依赖文件\r\nwebpack优势\r\n 是基于内存，哪个文件变了，单独编译哪个文件\r\nwebpack安装\r\n npm i webpack -g\r\nwebpack使用\r\n webpack 入口文件 输出文件\r\nwebpack 监视文件变化 自动化\r\n webpack 入口文件 输出文件 --watch\r\nwebpack配置文件\r\n 新建文件：webpack.config.js\r\n 里面是node代码\r\n module.exports={\r\n    entry:\'./entry.js\',\r\n    output:{\r\n       path:__dirname,\r\n       filename:\'bundle.js\'\r\n    }\r\n}\r\n安装webpack-dev-server\r\n npm install webpack-dev-server -g\r\n使用webpack-dev-server \r\n 命令行webpack-dev-server\r\nwebpack dev server\r\n 提供热更新服务，当js文件\r\n 发生变化时自动重新编译，并且刷新页面\r\n转换器\r\nwebpack默认只能载入原生的js文件\r\n使用：下载转换器\r\n npm install css-loader style-loader\r\n引用：require(\'!style!css!./xxx.css\')\r\n以后的开发已js为主\r\n', 'webpack打包', '2018-07-22', '2018-07-22');
INSERT INTO `user_data` VALUES ('undefine', '9', '1、安装java（1.8版本以上）\r\n    命令查看版本号（java -version）\r\n    配置环境变量JAVA_HOME\r\n2、安装android studio\r\n    配置环境变量ANDROID_HOME:\r\n    PATH里面添加环境变量 增加：安装目录sdk	ools、增加：安装目录sdkplatform-tools\r\n3、设置SDK\r\n    打开Android SDK Manager\r\n    选中以下的选项\r\n    tools\r\n     >Android SDK Tools (24.3.4)\r\n     >Android SDK Platform-tools (23.0.1)\r\n     >Android SDK Build-tools (23.0.1)\r\n    Android 6.0(API 23)\r\n     >SDK Platform 23 1\r\n     >intel x86 Atom_64 System Image 23 3\r\n     >intel x86 Atom System Image 23 3\r\n4、安装node（版本大于5.0）\r\n    命令查看node版本号（node -version）\r\n    命令查看npm版本号（npm -version）\r\n    更换淘宝镜像（npm install -g cnpm --registry=http://registry.npm.taobao.org）\r\n5、安装git\r\n    配置环境变量PATH 添加：安装目录安装文件名in\r\n6、安装react-native命令行工具react-naive-cli\r\n    新建文件夹（尽量不在C盘）名暂定为react_native\r\n    进入这个文件夹 命令行：git clone https://github.com/facebook/react-native.git（时间会很慢）\r\n    成功后找到刚下载的文件夹。进入的react-native目录下的react-native-cli目录 命令：npm install -g\r\n7、创建工程\r\n    进入你希望创建项目的目录后，输入react-native init XXX（项目名称），等待一段时间（较慢）\r\n    成功后会发现文件夹下多出很多文件夹和文件\r\n8、开启工程\r\n    进入工程目录 命令：react-native start\r\n    在浏览器中访问http://localhost:8081/index.android.bundle?platform=android\r\n9、运行项目\r\n    进入项目目录，输入react-native run-android（第一次会很慢）\r\n10、手机上显示\r\n    第一次一般会报错\r\n    这时候我们摇一摇手机，点击Dev Settings后，点击Debug server host & port for device,设置IP和端口\r\n    这里的IP是电脑的IP，不知道的可以在命令行中输入ipconfig进行查询，端口号固定8081  \r\n    设置完成后，回到空白页面，再次摇一摇手机，选择Reload JS，程序就运行起来，出现Welcome to React Native！', 'React Native', '0000-00-00', '0000-00-00');
